language: c
os: osx # OSX 10.12
osx_image: xcode9.1
sudo: false

before_install:
  - brew install lz4

script:
  - git tag
  - ls -l /usr/local/lib/*lz* 

deploy:
  provider: releases
  api-key:
    secure: $GITHUB_TOKEN
  file: "/usr/local/lib/liblz4.1.8.1.dylib"
  skip_cleanup: true
  on:
    tags: true
